name: _test

on:
  workflow_call:

jobs:
  Test:
    runs-on: ubuntu-latest
    container: node:19-alpine

    steps:
      - uses: actions/checkout@v3

      - name: Run Client Tests
        run: |
          cd trakky-client
          npm run build
          npm run test
